on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
   PERL_USE_UNSAFE_INC: 0
   AUTHOR_TESTING: 1
   AUTOMATED_TESTING: 1
   RELEASE_TESTING: 1
   PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

jobs:
  linux-integration:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:jammy

    steps:
      - run: apt update
      - run: apt install -y git gnupg cmake curl cpanminus pkg-config libanyevent-perl libssl-dev libzstd-dev
      - run: curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
      - run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org.list
      - run: apt update
      - run: apt install -y mongodb-org
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: mkdir data
      - run: mongod --bind_ip_all --noauth --logpath mongod.log --dbpath data --fork
      - run: cat mongod.log
      #- run: apt install -y lsof && lsof | grep IPv4
      - run: echo 'use admin' | mongosh mongodb://localhost

      #- run: cpanm --notest MongoDB
      #- run: perl -MMongoDB -MData::Dumper -e'print Dumper( MongoDB->connect("mongodb://localhost")->topology_status() )'

      # TODO: dedupe
      - name: Download & extract libmongoc
        run: curl -L https://github.com/mongodb/mongo-c-driver/releases/download/1.23.2/mongo-c-driver-1.23.2.tar.gz | tar -xzf -
      - name: Build & install libmongoc
        run: cd mongo-c-driver-1.23.2 && cmake -DENABLE_TRACING=ON . && make -j4 install && cd ..
      - run: rm -rf mongo-c-driver-1.23.2
      - run: ldconfig --verbose
      # end dedupe

      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: gcc example-simple.c -o example-simple $(pkg-config --cflags --libs libmongoc-1.0)
      - run: apt install -y strace
      - run: strace -fyy perl -MIO::Socket::INET -e'IO::Socket::INET->new("localhost:27017")'
      - run: strace -fyy perl -MSocket -Mautodie -e'socket my $s, AF_INET, SOCK_STREAM, 0; $s->blocking(0); CORE::connect($s, Socket::pack_sockaddr_in(27017, "\x7f\0\0\1")); vec( my $win, fileno($s), 1 ) = 1; select undef, $win, undef, undef; getsockopt($s, SOL_SOCKET, SO_ERROR)'
      - run: strace -fyy ./example-simple
      - run: gcc example-pool.c -o example-pool $(pkg-config --cflags --libs libmongoc-1.0)
      - run: ./example-pool
      - name: Install Dependencies
        run: cpanm --notest --installdeps --with-configure --with-develop --with-recommends --verbose .
      - run: perl Makefile.PL
      - run: make test
        env:
          MDXS_TEST_MONGODB_URI: 'mongodb://127.0.0.1'

  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
          - '5.18'
          - '5.16'
          - '5.14'
          - '5.12'
          - '5.10'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - run: apt install -y cmake
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: pwd
      - run: ls -la
      - name: Download & extract libmongoc
        run: curl -L https://github.com/mongodb/mongo-c-driver/releases/download/1.23.2/mongo-c-driver-1.23.2.tar.gz | tar -xzf -
      - name: Build & install libmongoc
        run: cd mongo-c-driver-1.23.2 && cmake . && make -j4 install && cd ..
      - run: rm -rf mongo-c-driver-1.23.2
      - run: pwd
      - run: ls -laR
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --notest --installdeps --with-configure --with-recommends --verbose .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: prove -wlvmb t

  linux-old-version:
    runs-on: ubuntu-latest

    container:
      image: perldocker/perl-tester

    steps:
      - run: apt install -y cmake
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - name: Download & extract libmongoc
        run: curl -L https://github.com/mongodb/mongo-c-driver/releases/download/1.20.0/mongo-c-driver-1.20.0.tar.gz | tar -xzf -
      - name: Build & install libmongoc
        run: cd mongo-c-driver-1.20.0 && cmake . && make install && cd ..
      - run: rm -rf mongo-c-driver-1.20.0
      - name: Install Dependencies
        run: cpanm --notest --installdeps --with-configure --with-develop --with-recommends --verbose .
      - name: perl Makefile.PL FAILS
        run: '! perl Makefile.PL'

  mac-dynamic:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - name: Set up Perl & libmongoc
        run: brew install libmongoc cpanminus
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --notest --installdeps --with-develop --with-configure --with-recommends --verbose .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - run: prove -wlvmb t
